import type { TvProduct } from "../../../../product-catalog/core/types";

const history = (...prices: number[]) => prices.map((lowestPrice, index) => ({ date: `2026-${String(index + 1).padStart(2, "0")}-01`, lowestPrice }));
const common = { dataStatus: "mock" as const, updatedAt: "2026-07-01" };

export const TV_PRODUCTS: TvProduct[] = [
  { ...common, id: "tv-google-55", categoryId: "tv", brand: "MOIT View", modelNumber: "MV-G55", name: "클리어 Google 55", imagePath: "/assets/products/mock/tv/tv-google-55.svg", shortInfo: "55인치 4K Google TV", aiReviewSummary: "더미 리뷰 요약: 앱 접근성과 균형 잡힌 화질이 좋다는 가상 평가예요.", currentPrice: 899_000, priceHistory: history(990_000, 950_000, 910_000, 870_000, 890_000, 899_000), strengths: ["3년 보증", "HDR"], weaknesses: ["VA 시야각"], specs: { os: "google-tv", resolution: "4k-uhd", screenSizeInches: 55, panel: "va", warrantyYears: 3, hdr: true, energyGrade: 1, mockRebateEligible: true } },
  { ...common, id: "tv-android-43", categoryId: "tv", brand: "한빛", modelNumber: "HB-A43", name: "스마트 안드로이드 43", imagePath: "/assets/products/mock/tv/tv-android-43.svg", shortInfo: "43인치 4K Android TV", aiReviewSummary: "더미 리뷰 요약: 작은 거실에서 가격 대비 기능이 충분하다는 가상 요약이에요.", currentPrice: 479_000, priceHistory: history(540_000, 510_000, 480_000, 450_000, 470_000, 479_000), strengths: ["낮은 가격", "IPS 패널"], weaknesses: ["보증 1년"], specs: { os: "android-tv", resolution: "4k-uhd", screenSizeInches: 43, panel: "ips", warrantyYears: 1, hdr: false, energyGrade: 2, mockRebateEligible: false } },
  { ...common, id: "tv-cinema-65", categoryId: "tv", brand: "누리전자", modelNumber: "NE-C65", name: "시네마 IPS 65", imagePath: "/assets/products/mock/tv/tv-cinema-65.svg", shortInfo: "65인치 4K IPS HDR", aiReviewSummary: "더미 리뷰 요약: 넓은 시야각과 HDR 영화 감상에 강점이 있다는 가상 평가예요.", currentPrice: 1_390_000, priceHistory: history(1_520_000, 1_470_000, 1_410_000, 1_350_000, 1_380_000, 1_390_000), strengths: ["IPS 시야각", "4년 보증"], weaknesses: ["평균보다 높은 가격"], specs: { os: "google-tv", resolution: "4k-uhd", screenSizeInches: 65, panel: "ips", warrantyYears: 4, hdr: true, energyGrade: 2, mockRebateEligible: true } },
  { ...common, id: "tv-big-75", categoryId: "tv", brand: "모아테크", modelNumber: "MT-Q75", name: "빅뷰 VA 75", imagePath: "/assets/products/mock/tv/tv-big-75.svg", shortInfo: "75인치 4K 대화면", aiReviewSummary: "더미 리뷰 요약: 대화면 명암은 좋지만 소비전력과 설치 공간 확인이 필요하다는 가상 의견이에요.", currentPrice: 1_790_000, priceHistory: history(2_050_000, 1_940_000, 1_850_000, 1_720_000, 1_760_000, 1_790_000), strengths: ["높은 명암", "HDR"], weaknesses: ["효율 3등급"], specs: { os: "android-tv", resolution: "4k-uhd", screenSizeInches: 75, panel: "va", warrantyYears: 2, hdr: true, energyGrade: 3, mockRebateEligible: false } },
  { ...common, id: "tv-basic-55", categoryId: "tv", brand: "데일리", modelNumber: "DY-F55", name: "베이직 FHD 55", imagePath: "/assets/products/mock/tv/tv-basic-55.svg", shortInfo: "55인치 Full HD 보급형", aiReviewSummary: "더미 리뷰 요약: 방송 시청은 무난하지만 4K 콘텐츠에는 부족하다는 가상 요약이에요.", currentPrice: 399_000, priceHistory: history(450_000, 430_000, 410_000, 390_000, 395_000, 399_000), strengths: ["매우 낮은 가격"], weaknesses: ["4K 아님", "기타 OS"], specs: { os: "other", resolution: "full-hd", screenSizeInches: 55, panel: "va", warrantyYears: 2, hdr: false, energyGrade: 3, mockRebateEligible: false } },
];
