import type { AirConditionerProduct } from "../../../../product-catalog/core/types";

const history = (...prices: number[]) => prices.map((lowestPrice, index) => ({ date: `2026-${String(index + 1).padStart(2, "0")}-01`, lowestPrice }));
const common = { dataStatus: "mock" as const, updatedAt: "2026-07-01" };

export const AIR_CONDITIONER_PRODUCTS: AirConditionerProduct[] = [
  { ...common, id: "ac-breeze-18", categoryId: "air-conditioner", brand: "MOIT Air", modelNumber: "MA-S18", name: "브리즈 스탠드 18", imagePath: "/assets/products/mock/air-conditioner/ac-breeze-18.svg", shortInfo: "18평형 인버터 스탠드형", aiReviewSummary: "더미 리뷰 요약: 냉방 속도와 자동 건조 편의성이 좋다는 가상 평가가 많아요.", currentPrice: 1_490_000, priceHistory: history(1_650_000, 1_590_000, 1_520_000, 1_470_000, 1_510_000, 1_490_000), strengths: ["공식 설치 가능", "자동 건조"], weaknesses: ["기본 설치비 별도"], specs: { type: "standing", ratedCoolingAreaPyeong: 18, inverter: true, basicInstallationIncluded: false, officialInstallation: true, autoDry: true, energyGrade: 1, mockRebateEligible: true } },
  { ...common, id: "ac-value-wall-8", categoryId: "air-conditioner", brand: "한빛", modelNumber: "HB-W08", name: "가성비 벽걸이 8", imagePath: "/assets/products/mock/air-conditioner/ac-value-wall-8.svg", shortInfo: "소형방용 8평 벽걸이", aiReviewSummary: "더미 리뷰 요약: 가격은 낮지만 정속형의 전력 부담을 주의해야 한다는 가상 의견이에요.", currentPrice: 429_000, priceHistory: history(480_000, 450_000, 420_000, 439_000, 429_000, 429_000), strengths: ["낮은 구매가", "설치비 포함"], weaknesses: ["인버터 아님", "공식 지정 설치 미지원"], specs: { type: "wall", ratedCoolingAreaPyeong: 8, inverter: false, basicInstallationIncluded: true, officialInstallation: false, autoDry: false, energyGrade: 4, mockRebateEligible: false } },
  { ...common, id: "ac-pure-wall-10", categoryId: "air-conditioner", brand: "누리전자", modelNumber: "NE-W10I", name: "퓨어 월 10", imagePath: "/assets/products/mock/air-conditioner/ac-pure-wall-10.svg", shortInfo: "자동 건조 인버터 10평형", aiReviewSummary: "더미 리뷰 요약: 침실용으로 조용하고 관리가 쉽다는 가상 요약이에요.", currentPrice: 780_000, priceHistory: history(850_000, 820_000, 790_000, 750_000, 770_000, 780_000), strengths: ["저소음", "설치비 포함"], weaknesses: ["효율 2등급"], specs: { type: "wall", ratedCoolingAreaPyeong: 10, inverter: true, basicInstallationIncluded: true, officialInstallation: true, autoDry: true, energyGrade: 2, mockRebateEligible: false } },
  { ...common, id: "ac-duo-20", categoryId: "air-conditioner", brand: "모아테크", modelNumber: "MT-D20", name: "듀오 2in1 20", imagePath: "/assets/products/mock/air-conditioner/ac-duo-20.svg", shortInfo: "거실·침실 2in1 고효율형", aiReviewSummary: "더미 리뷰 요약: 초기 비용은 높지만 두 공간 관리가 편하다는 가상 평가예요.", currentPrice: 2_390_000, priceHistory: history(2_590_000, 2_510_000, 2_420_000, 2_350_000, 2_410_000, 2_390_000), strengths: ["1등급", "기본 설치 포함"], weaknesses: ["높은 가격"], specs: { type: "two-in-one", ratedCoolingAreaPyeong: 20, inverter: true, basicInstallationIncluded: true, officialInstallation: true, autoDry: true, energyGrade: 1, mockRebateEligible: true } },
  { ...common, id: "ac-window-6", categoryId: "air-conditioner", brand: "윈드랩", modelNumber: "WL-C06", name: "윈도우 쿨 6", imagePath: "/assets/products/mock/air-conditioner/ac-window-6.svg", shortInfo: "자가 설치형 6평 창문형", aiReviewSummary: "더미 리뷰 요약: 설치는 간단하지만 소음과 냉방 면적이 제한적이라는 가상 의견이에요.", currentPrice: 599_000, priceHistory: history(670_000, 640_000, 610_000, 580_000, 590_000, 599_000), strengths: ["설치비 없음", "인버터"], weaknesses: ["자동 건조 없음", "소형 공간 전용"], specs: { type: "window", ratedCoolingAreaPyeong: 6, inverter: true, basicInstallationIncluded: true, officialInstallation: true, autoDry: false, energyGrade: 3, mockRebateEligible: false } },
];
